- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
     path: /usr/share/nginx/html/*
     state: absent

  - name: download frontend content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip


